# Generated by Django 4.0 on 2022-01-12 20:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('glossary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('headlines', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('timeline', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('womenintech', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('learning', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('myth', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gizmo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('faq', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('spot', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('performer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploadsimg/')),
            ],
        ),
    ]
