# Generated by Django 4.0 on 2022-01-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieeewie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsform',
            name='image',
        ),
        migrations.AddField(
            model_name='newsform',
            name='image_head',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='faq',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='gizmo',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='glossary',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='headlines',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='learning',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='month',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='myth',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='performer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='spot',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='summary',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='timeline',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='womenintech',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsform',
            name='year',
            field=models.CharField(default='', max_length=500),
        ),
    ]
