# Generated by Django 4.0 on 2022-01-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ieeewie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsform',
            old_name='image',
            new_name='image_head',
        ),
    ]
